branches:
  only:
  - master
language: java
jdk:
- oraclejdk8
script: cd ./modules && ant
defore_deploy:
- wget -O flex_sdk.zip http://mirrors.gigenet.com/apache/flex/4.14.1/binaries/apache-flex-sdk-4.14.1-bin.zip
- unzip -q flex_sdk.zip -d flex_sdk_win
- cp lib flex_sdk_win/liblc
- zip -r flex_sdk_win.zip flex_sdk_win
deploy:
  provider: releases
  api_key:
    secure: UV8Mro5LwKKGYvhTcIvfH/+ZRvUEsOATKnxXV8LWWxHeIJkwk8fCBCpKk4lEJ2Ft8UISz80MnN00ZYGukNZaU2KxmqSi2geqeANZFDRG+s7Ok4JH3P+s0wR5XZ80N9AkIu+RaLTlNMTo6zhnjsp/rZXqhoNcnsavVmwyamirueA=
  file: flex_sdk_win.zip
  skip_cleanup: true
  on:
    repo: code-orchestra/flex-sdk-livecoding