os: osx
env:
  APACHE_FLEX_SDK_URL=http://apache-mirror.rbc.ru/pub/apache/flex/4.15.0/binaries/apache-flex-sdk-4.15.0-bin.zip
  SDK_VERSION=4.15.0
language: objective-c
jdk:
  - oraclejdk8
before_script:
  - brew update >brew-update.log
  - brew install ant >brew-install.log
  - brew install 7zip
  - brew tap caskroom/cask
  - brew install brew-cask
  - brew cask install java
  - ant -version
  - java -version
script:
  - cd modules
  - ant
after_success:
  - cd $TRAVIS_BUILD_DIR
  - wget $APACHE_FLEX_SDK_URL -O apache_flex_sdk.zip
  - 7z x apache_flex_sdk.zip -oapache_flex_sdk
  - rm apache_flex_sdk.zip
  - mv lib apache_flex_sdk\liblc
  - 7z a flex_sdk_mac.zip apache_flex_sdk\
  - rm -rf apache_flex_sdk

