#branches:
#  only:
#    - master
#    - develop
language: java
jdk:
  - oraclejdk8
before_script:
  # Update Brew silently
  - brew update >brew-update.log
  # Install Brew Packages silently
  - brew install ant gradle >brew-install.log
script: gradle
