version: '{build}'
skip_tags: true
clone_depth: 10
clone_folder: C:\projects\CodeOrchestra\flex-sdk-livecoding
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
install:
   - cinst ant
build_script:
  - ant -version
  - java -version
  - cd C:\projects\CodeOrchestra\flex-sdk-livecoding\modules
  - ant
